/*
This file is automatically generated
LEMONMILK-Regular_12_ASTC
C Source
*/

#include "App_Common.h"

#define UNICODE_HANDLE   (1)

void LoadXfont()
{
	uint32_t fontAddr = RAM_G;

	// NOTE: Remember to write glyph file into BT815's flash at address 4096
	// Switch Flash to FULL Mode
	Gpu_CoCmd_FlashHelper_SwitchFullMode(phost);

	// Load xfont file into graphics RAM
	Gpu_Hal_LoadImageToMemory(phost, "path\\to\\LEMONMILK-Regular_12_ASTC.xfont", fontAddr, LOAD);
	Gpu_Hal_WaitCmdfifo_empty(phost);

	Gpu_CoCmd_Dlstart(phost);
	App_WrCoCmd_Buffer(phost, CLEAR(1, 1, 1));
	App_WrCoCmd_Buffer(phost, COLOR_RGB(255, 255, 255));

	Gpu_CoCmd_SetFont2(phost, UNICODE_HANDLE, fontAddr, 0);
	Gpu_CoCmd_Text(phost, 0, 0, UNICODE_HANDLE, 0, u8"Unicode Text to display");
	App_WrCoCmd_Buffer(phost, DISPLAY());
	Gpu_CoCmd_Swap(phost);
	App_Flush_Co_Buffer(phost);
	Gpu_Hal_WaitCmdfifo_empty(phost);
}

/* end of file */
